[package]
name = "prj"
version = "0.1.0"
authors = ["Jordan West <jordwest@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
git2 = "0.11.0"
dirs = "2.0"
serde = "1.0"
serde_derive = "1.0"
fuzzy-matcher = "0.3.1"
crossterm = "0.14.2"
